server:
  port: 8081

spring:
  application:
    name: movie-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include: health,info
