server:
  port: 9000

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth
    password: auth
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    org:
      springframework:
        security: DEBUG
