ALTER TABLE movies
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'DRAFT';

ALTER TABLE movies
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE movies
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();